In [37]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df=pd.read_csv(r"C:\Users\Dell\Documents\my_linux\repos\bank-telemarketing\banking-telemarketing\data\raw\bank+marketing\bank\bank-full.csv", sep=";")
display(df.shape, df.head(3))

(45211, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

In [39]:
#dfk = pd.read_csv(r"C:\Users\Dell\Documents\my_linux\repos\bank-telemarketing\banking-telemarketing\data\raw\bank+marketing\bank\bank.csv", sep=";")
#display(dfk.shape, dfk.head(3))

In [40]:
display(df.shape, df.info(), df.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

(45211, 17)

None

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no

In [41]:
display(df.job.unique(), df.marital.unique(), df.education.unique())

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

array(['married', 'single', 'divorced'], dtype=object)

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [42]:
display(df.poutcome.unique(), df.month.unique(), df.housing.unique(), df.default.unique())

array(['unknown', 'failure', 'other', 'success'], dtype=object)

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

array(['yes', 'no'], dtype=object)

array(['no', 'yes'], dtype=object)

In [43]:
display(df.duplicated().sum(), df.isna().sum())

0

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [44]:
display(df.poutcome.value_counts(), df.month.value_counts(), df.housing.value_counts(), df.default.value_counts())

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64

housing
yes    25130
no     20081
Name: count, dtype: int64

default
no     44396
yes      815
Name: count, dtype: int64

In [45]:
display(df.job.value_counts(), df.marital.value_counts(), df.education.value_counts())

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [46]:
# job, contact, campaign, pdays, 
dfk = df.drop(["job", "contact", "campaign", "pdays"], axis=1)
dfk.duplicated().sum()

0

In [47]:
dfk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   marital    45211 non-null  object
 2   education  45211 non-null  object
 3   default    45211 non-null  object
 4   balance    45211 non-null  int64
 5   housing    45211 non-null  object
 6   loan       45211 non-null  object
 7   day        45211 non-null  int64
 8   month      45211 non-null  object
 9   duration   45211 non-null  int64
 10  previous   45211 non-null  int64
 11  poutcome   45211 non-null  object
 12  y          45211 non-null  object
dtypes: int64(5), object(8)
memory usage: 4.5+ MB

In [52]:
# dfk.to_csv("cleaned.csv", index=False)